### ISSUE TITLE
Login Problem

### ISSUE THREAD

**Issue by SpaceLeft** [rovelstars/discord-list#242]
nader11ndeu#1712
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:558:11)
    at ServerResponse.header (/rbd/pnpm-volume/d88c03a7-8147-49ad-9307-4a5e4eea7ffc/node_modules/express/lib/response.js:771:10)
    at ServerResponse.append (/rbd/pnpm-volume/d88c03a7-8147-49ad-9307-4a5e4eea7ffc/node_modules/express/lib/response.js:732:15)
    at ServerResponse.res.cookie (/rbd/pnpm-volume/d88c03a7-8147-49ad-9307-4a5e4eea7ffc/node_modules/express/lib/response.js:857:8)
at /app/src/server/routes/authclient.js:74:9
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
An Error Occurred!
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client

**Comment by SpaceLeft** [comment]
Please Connect with me in discord `nader11ndeu#1712`

**Comment by sayantan300** [comment]
:/
Join our server, I won't connect you via DMs.

**Comment by sayantan300** [comment]
We can't work on the issue without providing much details.

**Comment by SpaceLeft** [comment]
you're site have this problem can't login!

**Comment by sayantan300** [comment]
Stop lying everywhere!
If this problem was with our site, how would you be notified about the error huh?
Also there's no api logging shown that you tried to login. It was your alts logging in.

**Comment by sayantan300** [comment]
Also I fixed this problem. This should be deleted then.
